### ISSUE TITLE
Scala 3 support?

### ISSUE THREAD

**Issue by ahjohannessen** [alejandrohdezma/http4s-munit#221]
I wonder if you have Scala 3 support in mind anytime soon? :)

**Comment by alejandrohdezma** [comment]
I do! I haven't had the time lately. I'll see if I can take a look at it later this week :)

Will keep you posted.

**Comment by bardurdam** [comment]
It seems to compile and test fine with scala 3.1.2, if kindprojector and sbt-scalafix-defaults plugin is disabled

**Comment by alejandrohdezma** [comment]
Hey @ahjohannessen, I just published version `0.10.0` with cross-publishing for Scala 3. Thanks @bardurdam for the help! 😄
